### ISSUE TITLE
Making JSONP Ajax request to external API

### ISSUE THREAD

**Issue by stevecreswick** [skipteel/position#1]
We are creating a stock market simulation API.  To show the user current information about stocks, we need to render information from an external API on our page.  I keep running into the error message: 

No 'Access-Control-Allow-Origin' header is present on the requested resource

After researching this error, it seems like it is a security protocol all browsers have preventing access across domains.  I have read that I can use JSONP to get around this, and our market API can export in JSONP, but I do not know how to do this, and reading tutorials and samples all day have no gotten me any closer to understanding how to access and render information this way.

**Comment by amadden80** [comment]
Did this get resolved?   JSONP etc can be a headache!   In our standup, it seemed you moved past here.

**Comment by stevecreswick** [comment]
Yeah, I think we moved past this and can access the data we need.  Thanks!
